# -*- coding: utf-8 -*-
"""AI Module.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UECS_MOGoMCUBV_x1K60AyKTZJkhJN_p
"""

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

# Load the data
def load_data(path: str = "/path_to_csv"):
  """
  This function takes a path to CSV file as a string and loads into a Pandas
  Dataframe
  :param    path: str, relative path of the CSV file
  :return   df: pd.DataFrame
  """
  df = pd.read_csv(f"{path}")
  df = df.drop(columns=["Umnamed: 0"], inplace=True, errors='ignore')
  return df

# Create target variable and predictor variables
def create_target_and_predictors(
    data: pd.DataFrame = None,
    target: str = "estimated_stock_pct"
):
  """
  This function takes in Panda DataFrame and splits it into a target column
  and a set of predictor variables, i.e. X & y.
  These two splits of the data will be used to train a supervised machine
  learning model.

  :param data: pd.DataFrame, dataframe containing data for the model
  :param target: str, target variable that will be needed to predict
  :return X: pd.DataFrame
          y: pd.Series
  """
  # Check to see if target is present in the data
  if target not in data.columns:
    raise Exception(f"Target: {target} is not present in the data")

  # Define the variables for target variable and prediction variables
  X = data.drop(columns=[target])
  y = data[target]
  return X, y